image: Ubuntu1804

stack: node 14

branches:
  only:
    - master

cache: node_modules

install:
  - pnpm install

build: off

build_script:
  - pnpm build

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - pnpm push-dir --dir=build --branch=gh-pages --force --verbose
